---
abstract: 'An interface to the YAJL JSON parsing and generation library'
author:
  - 'Leon Brocard <acme@astray.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-YAJL
provides:
  JSON::YAJL:
    file: lib/JSON/YAJL.pm
    version: 0.01
  JSON::YAJL::Generator:
    file: lib/JSON/YAJL/Generator.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
